# Generated by Django 5.0.6 on 2024-05-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0002_alter_organization_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
