# Generated by Django 5.0.6 on 2024-05-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0003_alter_organization_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="institution_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("educational_center", "EDUCATIONAL_CENTER"),
                    ("school", "SCHOOL"),
                    ("university", "UNIVERSITY"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
