# Generated by Django 5.0.6 on 2024-05-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organizations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("address", models.TextField()),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "institution_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("educational_center", "EDUCATIONAL_CENTER"),
                            ("school", "SCHOOL"),
                            ("university", "UNIVERSITY"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
        ),
    ]
